<?xml version='1.0' encoding='ISO-8859-1'?>

<!DOCTYPE SERVLET-POLICY [
<!-- The outer policy element --> 
<!ELEMENT policy (servlet-policy*)>
<!ATTLIST policy name CDATA #REQUIRED>
<!ATTLIST policy type CDATA #REQUIRED>

<!-- The servlet-policy element in which all the rules are contained -->
<!ELEMENT servlet-policy (failure-delay?,agent*,root?)>

<!-- The failure-delay element only supports a number -->
<!ELEMENT failure-delay (#PCDATA)>

<!-- The agent attributes specifies a rule for a particular Agent or
     all agents -->
<!ELEMENT agent (rule+)>
<!ATTLIST agent name CDATA #REQUIRED>

<!-- Each rule defines a set of uri patterns and roles that can access
     the uri patterns. -->
<!ELEMENT rule (pattern+,role+)>
<!ATTLIST rule requireSSL (true|false|yes|no) "false">
<!ATTLIST rule auth (CERT|PASSWORD|EITHER|BOTH) "EITHER">

<!-- Optionally an authorization type may be provided -->
<!ELEMENT auth (#PCDATA)>

<!-- The URI pattern that a rule applies to -->
<!ELEMENT pattern (#PCDATA)>

<!-- The roles that can access the patterns defined in the rule -->
<!ELEMENT role (#PCDATA)>

<!ELEMENT root (rule+)>
]>

<policy name="Servlet Policy" type="org.cougaar.core.security.policy.ServletPolicy">
  <servlet-policy>
    <!-- set the delay time (milliseconds) when a user fails -->
    <failure-delay>1000</failure-delay>

    <agent name="caAgent">
      <rule requireSSL="true">
        <!-- only let the administrator do write-only stuff -->
        <pattern>/CA/RevokeCertificateServlet</pattern>
        <role>CAAdministrator-AdminAssistant</role>
      </rule>
    </agent>

  </servlet-policy>

</policy>
