<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Communities [
<!ELEMENT Communities (Community+)>
<!ELEMENT Community (Attribute*, Entity*)>
<!ATTLIST Community Name CDATA #REQUIRED>
<!ELEMENT Entity (Attribute*)>
<!ATTLIST Entity Name CDATA #REQUIRED>
<!ELEMENT Attribute EMPTY>
<!ATTLIST Attribute ID CDATA #REQUIRED>
<!ATTLIST Attribute Value CDATA #REQUIRED>
]>
<Communities>
  <!--********************************************************
      *                                                      *
      *  1 A D - R E A R - C O M M                           *
      *                                                      *
      ********************************************************-->
  <Community Name="1AD-REAR-COMM" >
    <Attribute ID="CommunityType"             Value="Robustness" />
    <!-- Defines name of Robustness Manager node agent -->
    <Attribute ID="Manager"                   Value="REAR-A" />
    <!-- Number of agents expected to join community.  Robustness manager
         will generate a "Community Ready" CougaarEvent when the
         number of active agents in the community hits this level.  -->
    <Attribute ID="NumberOfAgents"            Value="73" />
    <!-- Parameter values used by Robustness Manager.  Parameters set for
         Entities override these values -->
    <Attribute ID="INITIAL_EXPIRATION"        Value="1200000" />
    <Attribute ID="ACTIVE_EXPIRATION"         Value="300000" />
    <Attribute ID="HEALTH_CHECK_EXPIRATION"   Value="30000" />
    <Attribute ID="DEAD_EXPIRATION"           Value="-1" />
    <Attribute ID="RESTART_EXPIRATION"        Value="180000" />
    <Attribute ID="FAILED_RESTART_EXPIRATION" Value="-1" />
    <Attribute ID="MOVE_EXPIRATION"           Value="300000" />
    <Attribute ID="PING_TIMEOUT"              Value="300000" />
    <Attribute ID="HEARTBEAT_REQUEST_TIMEOUT" Value="30000" />
    <Attribute ID="HEARTBEAT_FREQUENCY"       Value="15000" />
    <Attribute ID="HEARTBEAT_TIMEOUT"         Value="300000" />
    <Attribute ID="HEARTBEAT_PCT_OUT_OF_SPEC" Value="50" />
    <!-- Nodes -->
    <Entity Name="REAR-A" >
      <Attribute ID="EntityType" Value="Node" />
      <Attribute ID="Role" Value="Member" />
      <Attribute ID="Role" Value="HealthMonitor" />
    </Entity>
    <Entity Name="REAR-B" >
      <Attribute ID="EntityType" Value="Node" />
      <Attribute ID="Role" Value="Member" />
      <Attribute ID="Role" Value="HealthMonitor" />
    </Entity>
    <Entity Name="REAR-C" >
      <Attribute ID="EntityType" Value="Node" />
      <Attribute ID="Role" Value="Member" />
      <Attribute ID="Role" Value="HealthMonitor" />
    </Entity>
    <Entity Name="REAR-D" >
      <Attribute ID="EntityType" Value="Node" />
      <Attribute ID="Role" Value="Member" />
      <Attribute ID="Role" Value="HealthMonitor" />
    </Entity>
    <Entity Name="REAR-E" >
      <Attribute ID="EntityType" Value="Node" />
      <Attribute ID="Role" Value="Member" />
      <Attribute ID="Role" Value="HealthMonitor" />
    </Entity>
    <!-- Node REAR-A -->
    <Entity Name="NATO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="JSRCMDSE" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="USEUCOM" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="USAEUR" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="5-CORPS" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="HNS" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="5-CORPS-REAR" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="11-AVN-RGT" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="12-AVNBDE" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="130-ENGBDE" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="244-ENGBN-CBTHVY" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="52-ENGBN-CBTHVY" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="18-MPBDE" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="205-MIBDE" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="22-SIGBDE" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="30-MEDBDE" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="69-ADABDE" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="286-ADA-SCCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="5-CORPS-ARTY" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="41-FABDE" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="1-27-FABN" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="2-4-FABN-MLRS" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="3-13-FABN-155" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <!-- Node REAR-B -->
    <Entity Name="3-SUPCOM-HQ" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="19-MMC" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="208-SCCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="27-TCBN-MVTCTRL" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="7-CSG" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="316-POL-SUPPLYBN" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="515-POL-TRKCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="900-POL-SUPPLYCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="71-MAINTBN" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="240-SSCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="317-MAINTCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="565-RPRPTCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="597-MAINTCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="71-ORDCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <!-- Node REAR-C -->
    <Entity Name="125-ORDBN" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="452-ORDCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="529-ORDCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="181-TCBN" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="377-HVY-TRKCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="41-POL-TRKCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="51-MDM-TRKCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="561-SSBN" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="406-SUPPLYCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="541-POL-TRKCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="584-MAINTCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <!-- Node REAR-D -->
    <Entity Name="21-TSC-HQ" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="200-MMC" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="7-TCGP-TPTDD" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="AWR-2" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="RSA" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="37-TRANSGP" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="28-TCBN" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="109-MDM-TRKCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="66-MDM-TRKCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="68-MDM-TRKCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="6-TCBN" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="110-POL-SUPPLYCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="416-POL-TRKCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="632-MAINTCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <!-- Node REAR-E -->
    <Entity Name="29-SPTGP" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="191-ORDBN" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="23-ORDCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="24-ORDCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="702-EODDET" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="720-EODDET" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="51-MAINTBN" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="18-PERISH-SUBPLT" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="343-SUPPLYCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="5-MAINTCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="512-MAINTCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="574-SSCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
  </Community>
  <!--********************************************************
      *                                                      *
      *  1 A D - F W D - C O M M                             *
      *                                                      *
      ********************************************************-->
  <Community Name="1AD-FWD-COMM" >
    <Attribute ID="CommunityType"             Value="Robustness" />
    <Attribute ID="Manager"                   Value="FWD-A" />
    <Attribute ID="NumberOfAgents"            Value="55" />
    <Attribute ID="INITIAL_EXPIRATION"        Value="1200000" />
    <Attribute ID="ACTIVE_EXPIRATION"         Value="300000" />
    <Attribute ID="HEALTH_CHECK_EXPIRATION"   Value="30000" />
    <Attribute ID="DEAD_EXPIRATION"           Value="-1" />
    <Attribute ID="RESTART_EXPIRATION"        Value="180000" />
    <Attribute ID="FAILED_RESTART_EXPIRATION" Value="-1" />
    <Attribute ID="MOVE_EXPIRATION"           Value="300000" />
    <Attribute ID="PING_TIMEOUT"              Value="300000" />
    <Attribute ID="HEARTBEAT_REQUEST_TIMEOUT" Value="30000" />
    <Attribute ID="HEARTBEAT_FREQUENCY"       Value="15000" />
    <Attribute ID="HEARTBEAT_TIMEOUT"         Value="300000" />
    <Attribute ID="HEARTBEAT_PCT_OUT_OF_SPEC" Value="50" />
    <!-- Nodes -->
    <Entity Name="FWD-A" >
      <Attribute ID="EntityType" Value="Node" />
      <Attribute ID="Role" Value="Member" />
      <Attribute ID="Role" Value="HealthMonitor" />
    </Entity>
    <Entity Name="FWD-B" >
      <Attribute ID="EntityType" Value="Node" />
      <Attribute ID="Role" Value="Member" />
      <Attribute ID="Role" Value="HealthMonitor" />
    </Entity>
    <Entity Name="FWD-C" >
      <Attribute ID="EntityType" Value="Node" />
      <Attribute ID="Role" Value="Member" />
      <Attribute ID="Role" Value="HealthMonitor" />
    </Entity>
    <Entity Name="FWD-D" >
      <Attribute ID="EntityType" Value="Node" />
      <Attribute ID="Role" Value="Member" />
      <Attribute ID="Role" Value="HealthMonitor" />
    </Entity>
    <Entity Name="FWD-E" >
      <Attribute ID="EntityType" Value="Node" />
      <Attribute ID="Role" Value="Member" />
      <Attribute ID="Role" Value="HealthMonitor" />
    </Entity>
    <Entity Name="FWD-F" >
      <Attribute ID="EntityType" Value="Node" />
      <Attribute ID="Role" Value="Member" />
      <Attribute ID="Role" Value="HealthMonitor" />
    </Entity>
    <!-- Node FWD-A -->
    <Entity Name="1-AD" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="1-AD-DIV" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="1-4-ADABN" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="141-SIGBN" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="501-MIBN-CEWI" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="501-MPCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="69-CHEMCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="DIVARTY-1-AD" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="1-94-FABN" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="25-FABTRY-TGTACQ" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="DISCOM-1-AD" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="123-MSB" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <!-- Node FWD-B -->
    <Entity Name="1-BDE-1-AD" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="1-36-INFBN" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="1-37-ARBN" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="16-ENGBN" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="2-3-FABN" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="2-37-ARBN" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="501-FSB" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <!-- Node FWD-C -->
    <Entity Name="2-BDE-1-AD" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="1-35-ARBN" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="1-6-INFBN" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="2-6-INFBN" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="4-27-FABN" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="40-ENGBN" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="47-FSB" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <!-- Node FWD-D -->
    <Entity Name="3-BDE-1-AD" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="1-13-ARBN" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="1-41-INFBN" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="125-FSB" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="2-70-ARBN" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="4-1-FABN" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="70-ENGBN" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <!-- Node FWD-E -->
    <Entity Name="AVNBDE-1-AD" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="1-1-CAVSQDN" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="1-501-AVNBN" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="127-DASB" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="2-501-AVNBN" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <!-- Node FWD-F -->
    <Entity Name="16-CSG" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="485-CSB" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="102-POL-SUPPLYCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="26-SSCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="588-MAINTCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="592-ORDCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="596-MAINTCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="18-MAINTBN" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="226-MAINTCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="227-SUPPLYCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="263-FLDSVC-CO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="77-MAINTCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="106-TCBN" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="15-PLS-TRKCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="238-POL-TRKCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="372-CGO-TRANSCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="594-MDM-TRKCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
  </Community>
  <!--********************************************************
      *                                                      *
      *  1 A D - C O N U S - C O M M                         *
      *                                                      *
      ********************************************************-->
  <Community Name="1AD-CONUS-COMM" >
    <Attribute ID="CommunityType"             Value="Robustness" />
    <Attribute ID="Manager"                   Value="NCA-NODE" />
    <Attribute ID="NumberOfAgents"            Value="4" />
    <Attribute ID="INITIAL_EXPIRATION"        Value="1200000" />
    <Attribute ID="ACTIVE_EXPIRATION"         Value="300000" />
    <Attribute ID="HEALTH_CHECK_EXPIRATION"   Value="30000" />
    <Attribute ID="DEAD_EXPIRATION"           Value="-1" />
    <Attribute ID="RESTART_EXPIRATION"        Value="180000" />
    <Attribute ID="FAILED_RESTART_EXPIRATION" Value="-1" />
    <Attribute ID="MOVE_EXPIRATION"           Value="300000" />
    <Attribute ID="PING_TIMEOUT"              Value="300000" />
    <Attribute ID="HEARTBEAT_REQUEST_TIMEOUT" Value="30000" />
    <Attribute ID="HEARTBEAT_FREQUENCY"       Value="15000" />
    <Attribute ID="HEARTBEAT_TIMEOUT"         Value="300000" />
    <Attribute ID="HEARTBEAT_PCT_OUT_OF_SPEC" Value="50" />
    <!-- Nodes -->
    <Entity Name="NCA-NODE" >
      <Attribute ID="EntityType" Value="Node" />
      <Attribute ID="Role" Value="Member" />
      <Attribute ID="Role" Value="HealthMonitor" />
    </Entity>
    <Entity Name="CONUS-NODE" >
      <Attribute ID="EntityType" Value="Node" />
      <Attribute ID="Role" Value="Member" />
      <Attribute ID="Role" Value="HealthMonitor" />
    </Entity>
    <Entity Name="AGG-NODE" >
      <Attribute ID="EntityType" Value="Node" />
      <Attribute ID="Role" Value="Member" />
      <Attribute ID="Role" Value="HealthMonitor" />
    </Entity>
    <Entity Name="PLAN-NODE" >
      <Attribute ID="EntityType" Value="Node" />
      <Attribute ID="Role" Value="Member" />
      <Attribute ID="Role" Value="HealthMonitor" />
    </Entity>
    <!-- Node NCA-NODE -->
    <Entity Name="NCA" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <!-- Node CONUS-NODE -->
    <Entity Name="DLAHQ" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="OSC" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="FORSCOM" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <!-- Node AGG-NODE -->
    <Entity Name="AGG-Agent" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="DomainManager" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <!-- Node PLAN-NODE -->
    <Entity Name="PlanLogAgent" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
  </Community>
  <!--********************************************************
      *                                                      *
      *  1 A D - T R A N S - C O M M                         *
      *                                                      *
      ********************************************************-->
  <Community Name="1AD-TRANS-COMM" >
    <Attribute ID="CommunityType"             Value="Robustness" />
    <Attribute ID="Manager"                   Value="TRANSCOM-NODE" />
    <Attribute ID="NumberOfAgents"            Value="4" />
    <Attribute ID="INITIAL_EXPIRATION"        Value="1200000" />
    <Attribute ID="ACTIVE_EXPIRATION"         Value="300000" />
    <Attribute ID="HEALTH_CHECK_EXPIRATION"   Value="30000" />
    <Attribute ID="DEAD_EXPIRATION"           Value="-1" />
    <Attribute ID="RESTART_EXPIRATION"        Value="180000" />
    <Attribute ID="FAILED_RESTART_EXPIRATION" Value="-1" />
    <Attribute ID="MOVE_EXPIRATION"           Value="300000" />
    <Attribute ID="PING_TIMEOUT"              Value="600000" />
    <Attribute ID="HEARTBEAT_REQUEST_TIMEOUT" Value="30000" />
    <Attribute ID="HEARTBEAT_FREQUENCY"       Value="15000" />
    <Attribute ID="HEARTBEAT_TIMEOUT"         Value="600000" />
    <Attribute ID="HEARTBEAT_PCT_OUT_OF_SPEC" Value="50" />
    <!-- Nodes -->
    <Entity Name="TRANSCOM-NODE" >
      <Attribute ID="EntityType" Value="Node" />
      <Attribute ID="Role" Value="Member" />
      <Attribute ID="Role" Value="HealthMonitor" />
    </Entity>
    <Entity Name="AIR-NODE" >
      <Attribute ID="EntityType" Value="Node" />
      <Attribute ID="Role" Value="Member" />
      <Attribute ID="Role" Value="HealthMonitor" />
    </Entity>
    <Entity Name="SEA-NODE" >
      <Attribute ID="EntityType" Value="Node" />
      <Attribute ID="Role" Value="Member" />
      <Attribute ID="Role" Value="HealthMonitor" />
    </Entity>
    <Entity Name="THEATERTRANS-NODE" >
      <Attribute ID="EntityType" Value="Node" />
      <Attribute ID="Role" Value="Member" />
      <Attribute ID="Role" Value="HealthMonitor" />
    </Entity>
    <Entity Name="CONUSTRANS-NODE" >
      <Attribute ID="EntityType" Value="Node" />
      <Attribute ID="Role" Value="Member" />
      <Attribute ID="Role" Value="HealthMonitor" />
    </Entity>
    <!-- Node TRANSCOM-NODE -->
    <Entity Name="TRANSCOM" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <!-- Node AIR-NODE -->
    <Entity Name="GlobalAir" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="PlanePacker" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <!-- Node SEA-NODE -->
    <Entity Name="GlobalSea" >
      <Attribute ID="EntityType" Value="Agent" />