=== codeaudit/cougaar-securitycore/securityservices/test/configs/security/Policy.ldm.dtd
<!ELEMENT Policies (Policy*)>

<!ELEMENT Policy (RuleParam*)>
<!ATTLIST Policy name ID #REQUIRED>
<!ATTLIST Policy type CDATA #REQUIRED>

<!ELEMENT RuleParam (Double|Integer|String|Enumeration|Class|KeySet)>
<!ATTLIST RuleParam name ID #REQUIRED>

<!ELEMENT Double EMPTY>
<!ATTLIST Double value CDATA #REQUIRED>
<!ATTLIST Double min CDATA #REQUIRED>
<!ATTLIST Double max CDATA #REQUIRED>

<!ELEMENT Integer EMPTY>
<!ATTLIST Integer value CDATA #REQUIRED>
<!ATTLIST Integer min CDATA #REQUIRED>
<!ATTLIST Integer max CDATA #REQUIRED>

<!ELEMENT String EMPTY>
<!ATTLIST String value CDATA #REQUIRED>

<!ELEMENT Enumeration (EnumOption+)>
<!ATTLIST Enumeration value CDATA #REQUIRED>

<!ELEMENT EnumOption EMPTY>
<!ATTLIST EnumOption value CDATA #REQUIRED>

<!ELEMENT KeySet (KeyValue*)>
<!ATTLIST KeySet value CDATA #REQUIRED>

<!ELEMENT KeyValue (Double|Integer|String|Enumeration|Class|KeySet)>
<!ATTLIST KeyValue key ID #REQUIRED>
<!ATTLIST KeyValue value CDATA #REQUIRED>

<!ELEMENT Class EMPTY>
<!ATTLIST Class class_type CDATA #REQUIRED>

<!ELEMENT Boolean EMPTY>
<!ATTLIST Boolean value CDATA #REQUIRED>

=== codeaudit/cougaar-securitycore/securityservices/test/configs/ul-mini-config-openldap/TRANSCOMAccessControlPolicyThreat2.ldm.xml
<?xml version="1.0"  encoding="US-ASCII"?>

<!DOCTYPE Policy SYSTEM "Policy.ldm.dtd" []>

<Policies>

 <Policy name="TRANSCOMAccessControlPolicyThreat2" type="org.cougaar.core.security.policy.AccessControlPolicy">

	  <RuleParam name="IncomingMessageAction">
      	    <KeySet value="">
	      <KeyValue key="Criticality0" value="ForwardTo:ALPHA-AIRLINES" />
	      <KeyValue key="Criticality1" value="ForwardTo:ALPHA-AIRLINES" />
	      <KeyValue key="Criticality2" value="ForwardTo:ALPHA-AIRLINES" />
	      <KeyValue key="Criticality3" value="AcceptMessage" />
	      <KeyValue key="Criticality4" value="AcceptMessage" />
	      <KeyValue key="Criticality5" value="AcceptMessage" />
    	    </KeySet>
  	  </RuleParam>

    <RuleParam name="IncomingMessageCriticality">
      <KeySet value="2">
        <KeyValue key="2-7-INFBN" value="3" />
        <KeyValue key="3-69-ARBN" value="4" />
       <!-- <KeyValue key="3ID-HHC" value="4" />-->
      </KeySet>
    </RuleParam>

    <RuleParam name="IncomingMessageIntegrity">
      <KeySet value="2">
        <KeyValue key="2-7-INFBN" value="3" />
        <KeyValue key="3-69-ARBN" value="4" />
      </KeySet>
    </RuleParam>

</Policy>

</Policies>

=== codeaudit/cougaar-securitycore/securityservices/test/configs/ul-mini-config/2-BDE-3ID-HHCPolicy.ldm.xml
<?xml version="1.0"  encoding="US-ASCII"?>

<!DOCTYPE Policy SYSTEM "Policy.ldm.dtd" []>

<!-- Policies for 3ID-HHC -->

<Policies>

 <Policy name="TWO-BDE-3ID-HHCAccessControlPolicy" type="org.cougaar.core.security.AccessControlPolicy">

   <RuleParam name="agentName">
     <String value="2-BDE-3ID-HHC"> </String>
   </RuleParam>

    <RuleParam name="ThreatConLevel">
      <RangeSet value="">
        <RangeValue min="2" max="2">
	  <RuleParam name="IncomingMessageAction">
      	    <KeySet value="AcceptMessage">
    	    </KeySet>
  	  </RuleParam>
	</RangeValue>
        <RangeValue min="3" max="3">
	  <RuleParam name="IncomingMessageAction">
      	    <KeySet value="AcceptMessage">
    	    </KeySet>
  	  </RuleParam>
	</RangeValue>
      </RangeSet>
    </RuleParam>

    <RuleParam name="IncomingMessageCriticality">
      <KeySet value="4">
        <KeyValue key="2-7-INFBN" value="3" />
        <KeyValue key="3-69-ARBN" value="5" />
      </KeySet>
    </RuleParam>

    <RuleParam name="IncomingMessageIntegrity">
      <KeySet value="4">
        <KeyValue key="2-7-INFBN" value="3" />
        <KeyValue key="3-69-ARBN" value="5" />
      </KeySet>
    </RuleParam>

</Policy>

</Policies>

=== codeaudit/cougaar-securitycore/securityservices/test/configs/common/PS-TRANSCOM-Policy.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Policies SYSTEM "Policy.ldm.dtd" []>

<!-- Policies for BOOTPOLICY -->

<Policies>
 <Policy name="BOOTPOLICY" type="org.cougaar.core.security.policy.AccessControlPolicy">
  <RuleParam name="IncomingMessageAction">
    <KeySet value="">
      <KeyValue key="Criticality0" value="SetAside" />
      <KeyValue key="Criticality1" value="SetAside" />
      <KeyValue key="Criticality2" value="AcceptMessage" />
      <KeyValue key="Criticality3" value="AcceptMessage" />
      <KeyValue key="Criticality4" value="AcceptMessage" />
      <KeyValue key="Criticality5" value="AcceptMessage" />
    </KeySet>
  </RuleParam>

  <RuleParam name="IncomingVerb">
    <KeySet value="None">
	<!--<KeyValue key="TRANSCOM" value="GetLogSupport"/>-->
	<!--<KeyValue key="3-69-ARBN" value="Transport:ProjectSupply"/>-->
	<!--<KeyValue key="703-MSB" value="none"/>-->
    </KeySet>
  </RuleParam>

  <RuleParam name="OutgoingVerb">
    <KeySet value="*">
	<!--<KeyValue key="TRANSCOM" value="GetLogSupport"/>-->
	<!--<KeyValue key="3-69-ARBN" value="Transport:ProjectSupply"/>-->
	<!--<KeyValue key="703-MSB" value="none"/>-->
    </KeySet>
  </RuleParam>

  <RuleParam name="OutgoingAgentAction">
    <KeySet value="AcceptMessage">
      <!-- <KeyValue key="3-69-ARBN" value="SetAside" /> -->
      <!-- <KeyValue key="2-7-INFBN" value="SetAside" /> -->
    </KeySet>
  </RuleParam>

  <RuleParam name="IncomingAgentAction">
    <KeySet value="AcceptMessage">
      <!-- <KeyValue key="3-69-ARBN" value="SetAside" /> -->
      <!-- <KeyValue key="2-7-INFBN" value="SetAside" /> -->
    </KeySet>
  </RuleParam>

    <RuleParam name="IncomingMessageCriticality">
      <KeySet value="3">
      </KeySet>
    </RuleParam>

    <RuleParam name="OutgoingMessageCriticality">
      <KeySet value="3">
      </KeySet>
    </RuleParam>

    <RuleParam name="IncomingMessageIntegrity">
      <KeySet value="3">
      </KeySet>
    </RuleParam>

    <RuleParam name="OutgoingMessageIntegrity">
      <KeySet value="3">
      </KeySet>
    </RuleParam>

</Policy>

</Policies>

=== codeaudit/cougaar-securitycore/securityservices/test/configs/ul-mini-config-ldap/CENTCOM-HHCPolicy.ldm.xml
<?xml version="1.0"  encoding="US-ASCII"?>

<!DOCTYPE Policy SYSTEM "Policy.ldm.dtd" []>

<!-- Policies for CENTCOM-HHC -->

<Policies>

 <Policy name="CENTCOM-HHCCryptoPolicy" type="org.cougaar.core.security.CryptoPolicy">

   <!-- the following rule parameters will be used for the July demo -->

   <RuleParam name="secureMethod">
     <String value="signAndEncrypt"> </String>
   </RuleParam>

   <RuleParam name="symmetricAlgorithm">
     <String value="DESede"> </String>
   </RuleParam>

   <RuleParam name="asymmetricAlgorithm">
     <String value="RSA/ECB/PKCS#1"> </String>
   </RuleParam>

   <RuleParam name="signingAlgorithm">
     <String value="MD5withRSA"> </String>
   </RuleParam>

   <RuleParam name="messageSecurityManager">
     <String value="org.cougaar.core.society.PublicKeyMessageSecurityManager"> </String>
   </RuleParam>

   <RuleParam name="providerName">
     <String value=""> </String>
   </RuleParam>

 </Policy>

</Policies>

=== codeaudit/cougaar-securitycore/securityservices/test/configs/ul-mini-config-openldap/TRANSCOMPolicy.ldm.xml
<?xml version="1.0"  encoding="US-ASCII"?>

<!DOCTYPE Policy SYSTEM "Policy.ldm.dtd" []>

<!-- Policies for TRANSCOM -->

<Policies>

 <Policy name="TRANSCOMCryptoPolicy" type="org.cougaar.core.security.CryptoPolicy">

   <!-- the following rule parameters will be used for the July demo -->

   <RuleParam name="secureMethod">
     <KeySet value="sign">
       <KeyValue key="NCA" value="signAndEncrypt" />
       <KeyValue key="3ID-HHC" value="Encrypt" />
       <KeyValue key="ALPHA-AIRLINES" value="Encrypt" />
     </KeySet>
   </RuleParam>

   <RuleParam name="symmetricAlgorithm">
     <KeySet value="">
       <KeyValue key="NCA" value="DESede" />
       <KeyValue key="3ID-HHC" value="DESede" />
       <KeyValue key="ALPHA-AIRLINES" value="DES" />
     </KeySet>
   </RuleParam>

   <RuleParam name="asymmetricAlgorithm">
     <KeySet value="">
       <KeyValue key="NCA" value="RSA/ECB/PKCS#1" />
       <KeyValue key="3ID-HHC" value="RSA/ECB/PKCS#1" />
       <KeyValue key="ALPHA-AIRLINES" value="RSA/ECB/PKCS#1" />
     </KeySet>
   </RuleParam>

   <RuleParam name="signingAlgorithm">
     <KeySet value="MD5withRSA">
       <KeyValue key="NCA" value="MD5withRSA" />
       <KeyValue key="3ID-HHC" value="MD5withRSA" />
       <KeyValue key="ALPHA-AIRLINES" value="MD2withRSA" />
     </KeySet>
   </RuleParam>

   <RuleParam name="messageSecurityManager">
     <KeySet value="org.cougaar.core.society.PublicKeyMessageSecurityManager">
       <KeyValue key="NCA" value="org.cougaar.core.society.PublicKeyMessageSecurityManager" />
       <KeyValue key="3ID-HHC" value="org.cougaar.core.society.PublicKeyMessageSecurityManager" />
       <KeyValue key="ALPHA-AIRLINES" value="org.cougaar.core.society.PublicKeyMessageSecurityManager" />
     </KeySet>
   </RuleParam>

   <RuleParam name="providerName">
     <KeySet value="">
       <KeyValue key="NCA" value="" />
       <KeyValue key="3ID-HHC" value="" />
       <KeyValue key="ALPHA-AIRLINES" value="" />
     </KeySet>
   </RuleParam>

 </Policy>

 <Policy name="TRANSCOMAccessControlPolicy" type="org.cougaar.core.security.AccessControlPolicy">

   <RuleParam name="agentName">
     <String value="TRANSCOM"> </String>
   </RuleParam>

    <RuleParam name="ThreatConLevel">
      <RangeSet value="">
        <RangeValue min="2" max="2">
	  <RuleParam name="IncomingMessageAction">
      	    <KeySet value="">
	      <KeyValue key="Criticality0" value="ForwardTo:ALPHA-AIRLINES" />
	      <KeyValue key="Criticality1" value="ForwardTo:ALPHA-AIRLINES" />
	      <KeyValue key="Criticality2" value="ForwardTo:ALPHA-AIRLINES" />
	      <KeyValue key="Criticality3" value="AcceptMessage" />
	      <KeyValue key="Criticality4" value="AcceptMessage" />
	      <KeyValue key="Criticality5" value="AcceptMessage" />
    	    </KeySet>
  	  </RuleParam>
	</RangeValue>
        <RangeValue min="3" max="3">
	  <RuleParam name="IncomingMessageAction">
      	    <KeySet value="">
	      <KeyValue key="Criticality0" value="SetAside" />
	      <KeyValue key="Criticality1" value="SetAside" />
	      <KeyValue key="Criticality2" value="SetAside" />
	      <KeyValue key="Criticality3" value="SetAside" />
	      <KeyValue key="Criticality4" value="AcceptMessage" />
	      <KeyValue key="Criticality5" value="AcceptMessage" />
    	    </KeySet>
  	  </RuleParam>
	</RangeValue>
      </RangeSet>
    </RuleParam>

    <RuleParam name="IncomingMessageCriticality">
      <KeySet value="2">
        <KeyValue key="2-7-INFBN" value="3" />
        <KeyValue key="3-69-ARBN" value="4" />
       <!-- <KeyValue key="3ID-HHC" value="4" />-->
      </KeySet>
    </RuleParam>

    <RuleParam name="IncomingMessageIntegrity">
      <KeySet value="2">
        <KeyValue key="2-7-INFBN" value="3" />
        <KeyValue key="3-69-ARBN" value="4" />
      </KeySet>
    </RuleParam>

</Policy>

</Policies>

=== codeaudit/cougaar-securitycore/securityservices/test/configs/policygenerator/BootPolicyTemplate.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Policies SYSTEM "Policy.ldm.dtd" []>

<!-- Policies for BOOTPOLICY -->

<Policies>
   <Policy name="BOOTPOLICY" type="org.cougaar.core.security.policy.CryptoPolicy">
      <RuleParam name="IncomingSecureMethod">
         <KeySet value="signAndEncrypt"/>
      </RuleParam>
      <RuleParam name="OutgoingSecureMethod">
         <KeySet value="signAndEncrypt"/>
      </RuleParam>
      <RuleParam name="IncomingSymmetricAlgorithm">
         <KeySet value="DES"/>
      </RuleParam>
      <RuleParam name="OutgoingSymmetricAlgorithm">
         <KeySet value="DES"><!-- PKCS#1 is not supported by the Cryptix library --></KeySet>
      </RuleParam>
      <RuleParam name="IncomingAsymmetricAlgorithm">
         <!-- <KeySet value="RSA/ECB/PKCS5Padding"> -->
         <!-- <KeySet value="RSA/ECB/PKCS#1"> (cryptix)-->
         <!-- <KeySet value="RSA/ECB/PKCS1Padding"> -->
         <!-- <KeySet value="ElGamal/ECB/PKCS#1"> -->
         <KeySet value="RSA/ECB/PKCS#1"/>
      </RuleParam>
      <!-- used to encrypt the session key -->
      <RuleParam name="OutgoingAsymmetricAlgorithm">
         <!-- PKCS#1 is not supported by the Cryptix library -->
         <KeySet value="RSA/ECB/PKCS#1"/>
      </RuleParam>
      <RuleParam name="IncomingSigningAlgorithm">
         <!-- Example of possible values:          MD2withRSA, MD5withRSA, or SHA1withRSA -->
         <KeySet value="MD5withRSA"/>
      </RuleParam>
      <RuleParam name="OutgoingSigningAlgorithm">
         <KeySet value="MD5withRSA"/>
      </RuleParam>
   </Policy>

</Policies>

=== codeaudit/cougaar-securitycore/securityservices/test/configs/ul-mini-config-openldap/2-BDE-3ID-HHCAccessControlPolicyThreat3.ldm.xml
<?xml version="1.0"  encoding="US-ASCII"?>

<!DOCTYPE Policy SYSTEM "Policy.ldm.dtd" []>

<Policies>

 <Policy name="TWO-BDE-3ID-HHCAccessControlPolicyThreat3" type="org.cougaar.core.security.policy.AccessControlPolicy">

	  <RuleParam name="IncomingMessageAction">
      	    <KeySet value="AcceptMessage">
    	    </KeySet>
  	  </RuleParam>

    <RuleParam name="IncomingMessageCriticality">
      <KeySet value="4">
        <KeyValue key="2-7-INFBN" value="3" />
        <KeyValue key="3-69-ARBN" value="5" />
      </KeySet>
    </RuleParam>

    <RuleParam name="IncomingMessageIntegrity">
      <KeySet value="4">
        <KeyValue key="2-7-INFBN" value="3" />
        <KeyValue key="3-69-ARBN" value="5" />
      </KeySet>
    </RuleParam>

</Policy>


</Policies>

=== codeaudit/cougaar-securitycore/securityservices/test/configs/ul-mini-config-openldap/24-SPTGP-HHCPolicy.ldm.xml
<?xml version="1.0"  encoding="US-ASCII"?>

<!DOCTYPE Policy SYSTEM "Policy.ldm.dtd" []>

<!-- Policies for 24-SPTGP-HHC -->

<Policies>

 <Policy name="TWENTYFOUR-SPTGP-HHCAccessControlPolicy" type="org.cougaar.core.security.AccessControlPolicy">

   <RuleParam name="agentName">
     <String value="24-SPTGP-HHC"> </String>
   </RuleParam>

    <RuleParam name="ThreatConLevel">
      <RangeSet value="">
        <RangeValue min="2" max="2">
	  <RuleParam name="IncomingMessageAction">
      	    <KeySet value="AcceptMessage">
    	    </KeySet>
  	  </RuleParam>
	</RangeValue>
        <RangeValue min="3" max="3">
	  <RuleParam name="IncomingMessageAction">
      	    <KeySet value="AcceptMessage">
    	    </KeySet>
  	  </RuleParam>
	</RangeValue>
      </RangeSet>
    </RuleParam>

    <RuleParam name="IncomingMessageCriticality">
      <KeySet value="4">
        <KeyValue key="10-TCBN-HHC" value="3" />
      </KeySet>
    </RuleParam>

    <RuleParam name="IncomingMessageIntegrity">
      <KeySet value="4">
        <KeyValue key="10-TCBN-HHC" value="3" />
      </KeySet>
    </RuleParam>

 </Policy>

 <Policy name="TWENTYFOUR-SPTGP-HHCCryptoPolicy" type="org.cougaar.core.security.CryptoPolicy">

   <!-- the following rule parameters will be used for the July demo -->

   <RuleParam name="secureMethod">
     <String value="sign"> </String>
   </RuleParam>

   <RuleParam name="symmetricAlgorithm">
     <String value=""> </String>
   </RuleParam>

   <RuleParam name="asymmetricAlgorithm">
     <String value=""> </String>
   </RuleParam>

   <RuleParam name="signingAlgorithm">
     <String value="MD5withRSA"> </String>
   </RuleParam>

   <RuleParam name="messageSecurityManager">
     <String value="org.cougaar.core.society.PublicKeyMessageSecurityManager"> </String>
   </RuleParam>

   <RuleParam name="providerName">
     <String value=""> </String>
   </RuleParam>

 </Policy>

</Policies>
