=== codeaudit/cougaar-securitycore/securityservices/test/configs/security/Policy.ldm.dtd
<!ELEMENT Policies (Policy*)>

<!ELEMENT Policy (RuleParam*)>
<!ATTLIST Policy name ID #REQUIRED>
<!ATTLIST Policy type CDATA #REQUIRED>

<!ELEMENT RuleParam (Double|Integer|String|Enumeration|Class|KeySet)>
<!ATTLIST RuleParam name ID #REQUIRED>

<!ELEMENT Double EMPTY>
<!ATTLIST Double value CDATA #REQUIRED>
<!ATTLIST Double min CDATA #REQUIRED>
<!ATTLIST Double max CDATA #REQUIRED>

<!ELEMENT Integer EMPTY>
<!ATTLIST Integer value CDATA #REQUIRED>
<!ATTLIST Integer min CDATA #REQUIRED>
<!ATTLIST Integer max CDATA #REQUIRED>

<!ELEMENT String EMPTY>
<!ATTLIST String value CDATA #REQUIRED>

<!ELEMENT Enumeration (EnumOption+)>
<!ATTLIST Enumeration value CDATA #REQUIRED>

<!ELEMENT EnumOption EMPTY>
<!ATTLIST EnumOption value CDATA #REQUIRED>

<!ELEMENT KeySet (KeyValue*)>
<!ATTLIST KeySet value CDATA #REQUIRED>

<!ELEMENT KeyValue (Double|Integer|String|Enumeration|Class|KeySet)>
<!ATTLIST KeyValue key ID #REQUIRED>
<!ATTLIST KeyValue value CDATA #REQUIRED>

<!ELEMENT Class EMPTY>
<!ATTLIST Class class_type CDATA #REQUIRED>

<!ELEMENT Boolean EMPTY>
<!ATTLIST Boolean value CDATA #REQUIRED>

=== codeaudit/cougaar-securitycore/securityservices/test/configs/ul-mini-config/AccessControlPolicies.ldm.xml
<?xml version="1.0"  encoding="US-ASCII"?>

<!DOCTYPE Policy SYSTEM "Policy.ldm.dtd" []>

<Policies>
 <Policy name="TEN-TCBN-HHCAccessControlPolicy" type="org.cougaar.core.security.policy.AccessControlPolicy">

   <RuleParam name="agentName">
     <String value="10-TCBN-HHC"> </String>
   </RuleParam>

    <RuleParam name="OutgoingMessageCriticality">
      <Integer min="0" max="5" value="5" />
    </RuleParam>
    <RuleParam name="OutgoingMessageIntegrity">
      <Integer min="0" max="5" value="5" />
    </RuleParam>
 </Policy>



 <Policy name="TWENTYFOUR-SPTGP-HHCAccessControlPolicy" type="org.cougaar.core.security.policy.AccessControlPolicy">

   <RuleParam name="agentName">
     <String value="24-SPTGP-HHC"> </String>
   </RuleParam>

    <RuleParam name="ThreatConLevel">
      <RangeSet value="">
        <RangeValue min="2" max="2">
	  <RuleParam name="IncomingMessageAction">
      	    <KeySet value="AcceptMessage">
    	    </KeySet>
  	  </RuleParam>
	</RangeValue>
        <RangeValue min="3" max="3">
	  <RuleParam name="IncomingMessageAction">
      	    <KeySet value="AcceptMessage">
    	    </KeySet>
  	  </RuleParam>
	</RangeValue>
      </RangeSet>
    </RuleParam>

    <RuleParam name="IncomingMessageCriticality">
      <KeySet value="4">
        <KeyValue key="10-TCBN-HHC" value="3" />
      </KeySet>
    </RuleParam>

    <RuleParam name="IncomingMessageIntegrity">
      <KeySet value="4">
        <KeyValue key="10-TCBN-HHC" value="3" />
      </KeySet>
    </RuleParam>

 </Policy>


 <Policy name="TWO-SEVEN-INFBNAccessControlPolicy" type="org.cougaar.core.security.policy.AccessControlPolicy">

   <RuleParam name="agentName">
     <String value="2-7-INFBN"> </String>
   </RuleParam>

    <RuleParam name="OutgoingMessageCriticality">
      <Integer min="0" max="5" value="3" />
    </RuleParam>
    <RuleParam name="OutgoingMessageIntegrity">
      <Integer min="0" max="5" value="3" />
    </RuleParam>
 </Policy>


 <Policy name="TWO-BDE-3ID-HHCAccessControlPolicy" type="org.cougaar.core.security.policy.AccessControlPolicy">

   <RuleParam name="agentName">
     <String value="2-BDE-3ID-HHC"> </String>
   </RuleParam>

    <RuleParam name="ThreatConLevel">
      <RangeSet value="">
        <RangeValue min="2" max="2">
	  <RuleParam name="IncomingMessageAction">
      	    <KeySet value="AcceptMessage">
    	    </KeySet>
  	  </RuleParam>
	</RangeValue>
        <RangeValue min="3" max="3">
	  <RuleParam name="IncomingMessageAction">
      	    <KeySet value="AcceptMessage">
    	    </KeySet>
  	  </RuleParam>
	</RangeValue>
      </RangeSet>
    </RuleParam>

    <RuleParam name="IncomingMessageCriticality">
      <KeySet value="4">
        <KeyValue key="2-7-INFBN" value="3" />
        <KeyValue key="3-69-ARBN" value="5" />
      </KeySet>
    </RuleParam>

    <RuleParam name="IncomingMessageIntegrity">
      <KeySet value="4">
        <KeyValue key="2-7-INFBN" value="3" />
        <KeyValue key="3-69-ARBN" value="5" />
      </KeySet>
    </RuleParam>

</Policy>


 <Policy name="THREE-69-ARBNAccessControlPolicy" type="org.cougaar.core.security.policy.AccessControlPolicy">

   <RuleParam name="agentName">
     <String value="3-69-ARBN"> </String>
   </RuleParam>

    <RuleParam name="OutgoingMessageCriticality">
      <Integer min="0" max="5" value="4" />
    </RuleParam>
    <RuleParam name="OutgoingMessageIntegrity">
      <Integer min="0" max="5" value="4" />
    </RuleParam>
 </Policy>


 <Policy name="THREE-BDE-2IDHHCAccessControlPolicy" type="org.cougaar.core.security.policy.AccessControlPolicy">

   <RuleParam name="agentName">
     <String value="3-BDE-2ID-HHC"> </String>
   </RuleParam>

    <RuleParam name="ThreatConLevel">
      <RangeSet value="">
        <RangeValue min="2" max="2">
	  <RuleParam name="IncomingMessageAction">
      	    <KeySet value="AcceptMessage">
    	    </KeySet>
  	  </RuleParam>
	</RangeValue>
        <RangeValue min="3" max="3">
	  <RuleParam name="IncomingMessageAction">
      	    <KeySet value="AcceptMessage">
    	    </KeySet>
  	  </RuleParam>
	</RangeValue>
      </RangeSet>
    </RuleParam>

    <RuleParam name="IncomingMessageCriticality">
      <KeySet value="4">
      </KeySet>
    </RuleParam>

    <RuleParam name="IncomingMessageIntegrity">
      <KeySet value="4">
      </KeySet>
    </RuleParam>

 </Policy>


 <Policy name="THREEID-HHCAccessControlPolicy" type="org.cougaar.core.security.policy.AccessControlPolicy">

   <RuleParam name="agentName">
     <String value="3ID-HHC"> </String>
   </RuleParam>

    <!--RuleParam name="ThreatConLevel">
      <RangeSet value="">
        <RangeValue min="2" max="2">
	  <RuleParam name="IncomingMessageAction">
      	    <KeySet value="">
	      <KeyValue key="Criticality0" value="ForwardTo:ALPHA-AIRLINES" />
	      <KeyValue key="Criticality1" value="ForwardTo:ALPHA-AIRLINES" />
	      <KeyValue key="Criticality2" value="ForwardTo:ALPHA-AIRLINES" />
	      <KeyValue key="Criticality3" value="AcceptMessage" />
	      <KeyValue key="Criticality4" value="AcceptMessage" />
	      <KeyValue key="Criticality5" value="AcceptMessage" />
    	    </KeySet>
  	  </RuleParam>
	</RangeValue>
        <RangeValue min="3" max="3">
	  <RuleParam name="IncomingMessageAction">
      	    <KeySet value="">
	      <KeyValue key="Criticality0" value="SetAside" />
	      <KeyValue key="Criticality1" value="SetAside" />
	      <KeyValue key="Criticality2" value="SetAside" />
	      <KeyValue key="Criticality3" value="SetAside" />
	      <KeyValue key="Criticality4" value="AcceptMessage" />
	      <KeyValue key="Criticality5" value="AcceptMessage" />
    	    </KeySet>
  	  </RuleParam>
	</RangeValue>
      </RangeSet>
    </RuleParam-->

    <RuleParam name="OutgoingMessageCriticality">
      <KeySet value="2">
        <KeyValue key="2-7-INFBN" value="3" />
        <KeyValue key="3-69-ARBN" value="4" />
      </KeySet>
    </RuleParam>

    <RuleParam name="OutgoingMessageIntegrity">
      <KeySet value="2">
        <KeyValue key="2-7-INFBN" value="3" />
        <KeyValue key="3-69-ARBN" value="4" />
      </KeySet>
    </RuleParam>

</Policy>


 <Policy name="TRANSCOMAccessControlPolicy" type="org.cougaar.core.security.policy.AccessControlPolicy">

   <RuleParam name="agentName">
     <String value="TRANSCOM"> </String>
   </RuleParam>

    <RuleParam name="ThreatConLevel">
      <RangeSet value="">
        <RangeValue min="2" max="2">
	  <RuleParam name="IncomingMessageAction">
      	    <KeySet value="">
	      <KeyValue key="Criticality0" value="ForwardTo:ALPHA-AIRLINES" />
	      <KeyValue key="Criticality1" value="ForwardTo:ALPHA-AIRLINES" />
	      <KeyValue key="Criticality2" value="ForwardTo:ALPHA-AIRLINES" />
	      <KeyValue key="Criticality3" value="AcceptMessage" />
	      <KeyValue key="Criticality4" value="AcceptMessage" />
	      <KeyValue key="Criticality5" value="AcceptMessage" />
    	    </KeySet>
  	  </RuleParam>
	</RangeValue>
        <RangeValue min="3" max="3">
	  <RuleParam name="IncomingMessageAction">
      	    <KeySet value="">
	      <KeyValue key="Criticality0" value="SetAside" />
	      <KeyValue key="Criticality1" value="SetAside" />
	      <KeyValue key="Criticality2" value="SetAside" />
	      <KeyValue key="Criticality3" value="SetAside" />
	      <KeyValue key="Criticality4" value="AcceptMessage" />
	      <KeyValue key="Criticality5" value="AcceptMessage" />
    	    </KeySet>
  	  </RuleParam>
	</RangeValue>
      </RangeSet>
    </RuleParam>

    <RuleParam name="IncomingMessageCriticality">
      <KeySet value="2">
        <KeyValue key="2-7-INFBN" value="3" />
        <KeyValue key="3-69-ARBN" value="4" />
       <!-- <KeyValue key="3ID-HHC" value="4" />-->
      </KeySet>
    </RuleParam>

    <RuleParam name="IncomingMessageIntegrity">
      <KeySet value="2">
        <KeyValue key="2-7-INFBN" value="3" />
        <KeyValue key="3-69-ARBN" value="4" />
      </KeySet>
    </RuleParam>

</Policy>

</Policies>

=== codeaudit/cougaar-securitycore/securityservices/test/configs/ul-mini-config-openldap/3-BDE-2ID-HHCAccessControlPolicyThreat3.ldm.xml
<?xml version="1.0"  encoding="US-ASCII"?>

<!DOCTYPE Policy SYSTEM "Policy.ldm.dtd" []>

<Policies>

 <Policy name="THREE-BDE-2IDHHCAccessControlPolicyThreat3" type="org.cougaar.core.security.policy.AccessControlPolicy">

	  <RuleParam name="IncomingMessageAction">
      	    <KeySet value="AcceptMessage">
    	    </KeySet>
  	  </RuleParam>

    <RuleParam name="IncomingMessageCriticality">
      <KeySet value="4">
      </KeySet>
    </RuleParam>

    <RuleParam name="IncomingMessageIntegrity">
      <KeySet value="4">
      </KeySet>
    </RuleParam>

 </Policy>

</Policies>

=== codeaudit/cougaar-securitycore/securityservices/test/configs/ul-mini-config/3ID-HHCAccessControlPolicy.ldm.xml
<?xml version="1.0"  encoding="US-ASCII"?>

<!DOCTYPE Policy SYSTEM "Policy.ldm.dtd" []>

<Policies>

 <Policy name="3ID-HHCAccessControlPolicy" type="org.cougaar.core.security.policy.AccessControlPolicy">

    <RuleParam name="OutgoingMessageCriticality">
      <KeySet value="2">
        <KeyValue key="2-7-INFBN" value="3" />
        <KeyValue key="3-69-ARBN" value="4" />
      </KeySet>
    </RuleParam>

    <RuleParam name="OutgoingMessageIntegrity">
      <KeySet value="2">
        <KeyValue key="2-7-INFBN" value="3" />
        <KeyValue key="3-69-ARBN" value="4" />
      </KeySet>
    </RuleParam>

</Policy>

</Policies>

=== codeaudit/cougaar-securitycore/securityservices/test/configs/ul-mini-config-ldap/24-SPTGP-HHCAccessControlPolicy.ldm.xml
<?xml version="1.0"  encoding="US-ASCII"?>

<!DOCTYPE Policy SYSTEM "Policy.ldm.dtd" []>

<Policies>

 <Policy name="24-SPTGP-HHCAccessControlPolicy" type="org.cougaar.core.security.policy.AccessControlPolicy">

	  <RuleParam name="IncomingMessageAction">
      	    <KeySet value="AcceptMessage">
    	    </KeySet>
  	  </RuleParam>

    <RuleParam name="IncomingMessageCriticality">
      <KeySet value="4">
        <KeyValue key="10-TCBN-HHC" value="3" />
      </KeySet>
    </RuleParam>

    <RuleParam name="IncomingMessageIntegrity">
      <KeySet value="4">
        <KeyValue key="10-TCBN-HHC" value="3" />
      </KeySet>
    </RuleParam>

 </Policy>

</Policies>
