=== codeaudit/cougaar-securitycore/securityservices/test/configs/security/Policy.ldm.dtd
<!ELEMENT Policies (Policy*)>

<!ELEMENT Policy (RuleParam*)>
<!ATTLIST Policy name ID #REQUIRED>
<!ATTLIST Policy type CDATA #REQUIRED>

<!ELEMENT RuleParam (Double|Integer|String|Enumeration|Class|KeySet)>
<!ATTLIST RuleParam name ID #REQUIRED>

<!ELEMENT Double EMPTY>
<!ATTLIST Double value CDATA #REQUIRED>
<!ATTLIST Double min CDATA #REQUIRED>
<!ATTLIST Double max CDATA #REQUIRED>

<!ELEMENT Integer EMPTY>
<!ATTLIST Integer value CDATA #REQUIRED>
<!ATTLIST Integer min CDATA #REQUIRED>
<!ATTLIST Integer max CDATA #REQUIRED>

<!ELEMENT String EMPTY>
<!ATTLIST String value CDATA #REQUIRED>

<!ELEMENT Enumeration (EnumOption+)>
<!ATTLIST Enumeration value CDATA #REQUIRED>

<!ELEMENT EnumOption EMPTY>
<!ATTLIST EnumOption value CDATA #REQUIRED>

<!ELEMENT KeySet (KeyValue*)>
<!ATTLIST KeySet value CDATA #REQUIRED>

<!ELEMENT KeyValue (Double|Integer|String|Enumeration|Class|KeySet)>
<!ATTLIST KeyValue key ID #REQUIRED>
<!ATTLIST KeyValue value CDATA #REQUIRED>

<!ELEMENT Class EMPTY>
<!ATTLIST Class class_type CDATA #REQUIRED>

<!ELEMENT Boolean EMPTY>
<!ATTLIST Boolean value CDATA #REQUIRED>

=== codeaudit/cougaar-securitycore/securityservices/test/configs/ul-mini-config-openldap/3-BDE-2ID-HHCPolicy.ldm.xml
<?xml version="1.0"  encoding="US-ASCII"?>

<!DOCTYPE Policy SYSTEM "Policy.ldm.dtd" []>

<!-- Policies for 3-BDE-2ID-HHC -->

<Policies>

 <Policy name="THREE-BDE-2IDHHCAccessControlPolicy" type="org.cougaar.core.security.AccessControlPolicy">

   <RuleParam name="agentName">
     <String value="3-BDE-2ID-HHC"> </String>
   </RuleParam>

    <RuleParam name="ThreatConLevel">
      <RangeSet value="">
        <RangeValue min="2" max="2">
	  <RuleParam name="IncomingMessageAction">
      	    <KeySet value="AcceptMessage">
    	    </KeySet>
  	  </RuleParam>
	</RangeValue>
        <RangeValue min="3" max="3">
	  <RuleParam name="IncomingMessageAction">
      	    <KeySet value="AcceptMessage">
    	    </KeySet>
  	  </RuleParam>
	</RangeValue>
      </RangeSet>
    </RuleParam>

    <RuleParam name="IncomingMessageCriticality">
      <KeySet value="4">
      </KeySet>
    </RuleParam>

    <RuleParam name="IncomingMessageIntegrity">
      <KeySet value="4">
      </KeySet>
    </RuleParam>

 </Policy>

 <Policy name="THREE-BDE-2ID-HHCCryptoPolicy" type="org.cougaar.core.security.CryptoPolicy">

   <!-- the following rule parameters will be used for the July demo -->

   <RuleParam name="secureMethod">
     <String value="sign"> </String>
   </RuleParam>

   <RuleParam name="symmetricAlgorithm">
     <String value=""> </String>
   </RuleParam>

   <RuleParam name="asymmetricAlgorithm">
     <String value=""> </String>
   </RuleParam>

   <RuleParam name="signingAlgorithm">
     <String value="MD5withRSA"> </String>
   </RuleParam>

   <RuleParam name="messageSecurityManager">
     <String value="org.cougaar.core.society.PublicKeyMessageSecurityManager"> </String>
   </RuleParam>

   <RuleParam name="providerName">
     <String value=""> </String>
   </RuleParam>

 </Policy>

</Policies>

=== codeaudit/cougaar-securitycore/securityservices/test/configs/ul-mini-config/3-BDE-2IDHHCAccessControlPolicy.ldm.xml
<?xml version="1.0"  encoding="US-ASCII"?>

<!DOCTYPE Policy SYSTEM "Policy.ldm.dtd" []>

<Policies>

 <Policy name="3-BDE-2IDHHCAccessControlPolicy" type="org.cougaar.core.security.policy.AccessControlPolicy">

   <RuleParam name="agentName">
     <String value="3-BDE-2ID-HHC"> </String>
   </RuleParam>

    <RuleParam name="ThreatConLevel">
      <RangeSet value="">
        <RangeValue min="2" max="2">
	  <RuleParam name="IncomingMessageAction">
      	    <KeySet value="AcceptMessage">
    	    </KeySet>
  	  </RuleParam>
	</RangeValue>
        <RangeValue min="3" max="3">
	  <RuleParam name="IncomingMessageAction">
      	    <KeySet value="AcceptMessage">
    	    </KeySet>
  	  </RuleParam>
	</RangeValue>
      </RangeSet>
    </RuleParam>

    <RuleParam name="IncomingMessageCriticality">
      <KeySet value="4">
      </KeySet>
    </RuleParam>

    <RuleParam name="IncomingMessageIntegrity">
      <KeySet value="4">
      </KeySet>
    </RuleParam>

 </Policy>

</Policies>

=== codeaudit/cougaar-securitycore/securityservices/test/configs/ul-mini-config/3ID-HHCPolicy.ldm.xml
<?xml version="1.0"  encoding="US-ASCII"?>

<!DOCTYPE Policy SYSTEM "Policy.ldm.dtd" []>

<!-- Policies for 3ID-HHC -->

<Policies>

 <Policy name="THREEID-HHCCryptoPolicy" type="org.cougaar.core.security.CryptoPolicy">

   <!-- the following rule parameters will be used for the July demo -->

   <RuleParam name="secureMethod">
     <String value="signAndEncrypt"> </String>
   </RuleParam>

   <RuleParam name="symmetricAlgorithm">
     <String value="DESede"> </String>
   </RuleParam>

   <RuleParam name="asymmetricAlgorithm">
     <String value="RSA/ECB/PKCS#1"> </String>
   </RuleParam>

   <RuleParam name="signingAlgorithm">
     <String value="MD5withRSA"> </String>
   </RuleParam>

   <RuleParam name="messageSecurityManager">
     <String value="org.cougaar.core.society.PublicKeyMessageSecurityManager"> </String>
   </RuleParam>

   <RuleParam name="providerName">
     <String value=""> </String>
   </RuleParam>

 </Policy>

 <Policy name="THREEID-HHCAccessControlPolicy" type="org.cougaar.core.security.AccessControlPolicy">

   <RuleParam name="agentName">
     <String value="3ID-HHC"> </String>
   </RuleParam>

    <!--RuleParam name="ThreatConLevel">
      <RangeSet value="">
        <RangeValue min="2" max="2">
	  <RuleParam name="IncomingMessageAction">
      	    <KeySet value="">
	      <KeyValue key="Criticality0" value="ForwardTo:ALPHA-AIRLINES" />
	      <KeyValue key="Criticality1" value="ForwardTo:ALPHA-AIRLINES" />
	      <KeyValue key="Criticality2" value="ForwardTo:ALPHA-AIRLINES" />
	      <KeyValue key="Criticality3" value="AcceptMessage" />
	      <KeyValue key="Criticality4" value="AcceptMessage" />
	      <KeyValue key="Criticality5" value="AcceptMessage" />
    	    </KeySet>
  	  </RuleParam>
	</RangeValue>
        <RangeValue min="3" max="3">
	  <RuleParam name="IncomingMessageAction">
      	    <KeySet value="">
	      <KeyValue key="Criticality0" value="SetAside" />
	      <KeyValue key="Criticality1" value="SetAside" />
	      <KeyValue key="Criticality2" value="SetAside" />
	      <KeyValue key="Criticality3" value="SetAside" />
	      <KeyValue key="Criticality4" value="AcceptMessage" />
	      <KeyValue key="Criticality5" value="AcceptMessage" />
    	    </KeySet>
  	  </RuleParam>
	</RangeValue>
      </RangeSet>
    </RuleParam-->

    <RuleParam name="OutgoingMessageCriticality">
      <KeySet value="2">
        <KeyValue key="2-7-INFBN" value="3" />
        <KeyValue key="3-69-ARBN" value="4" />
      </KeySet>
    </RuleParam>

    <RuleParam name="OutgoingMessageIntegrity">
      <KeySet value="2">
        <KeyValue key="2-7-INFBN" value="3" />
        <KeyValue key="3-69-ARBN" value="4" />
      </KeySet>
    </RuleParam>

</Policy>

<!--</Policies>




    <RuleParam name="OutgoingMessageCriticality">
     <KeySet value="2">
       <KeyValue key="2-7-INFBN" value="3" />
       <KeyValue key="3-69-ARBN" value="4" />
     </KeySet>
   </RuleParam>
    <RuleParam name="OutgoingMessageIntegrity">
     <KeySet value="2">
       <KeyValue key="2-7-INFBN" value="3" />
       <KeyValue key="3-69-ARBN" value="4" />
     </KeySet>
    </RuleParam>
 </Policy> -->

</Policies>

=== codeaudit/cougaar-securitycore/securityservices/test/configs/common/BootPolicy-plain.ldm.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Policies SYSTEM "Policy.ldm.dtd" []>

<!-- Policies for BOOTPOLICY -->

<Policies>
   <Policy name="BOOTPOLICY" type="org.cougaar.core.security.policy.CryptoPolicy">
      <RuleParam name="IncomingSecureMethod">
         <KeySet value="plain"/>
      </RuleParam>
      <RuleParam name="OutgoingSecureMethod">
         <KeySet value="plain"/>
      </RuleParam>
      <RuleParam name="IncomingSymmetricAlgorithm">
         <KeySet value="DES"/>
      </RuleParam>
      <RuleParam name="OutgoingSymmetricAlgorithm">
         <KeySet value="DES"><!-- PKCS#1 is not supported by the Cryptix library --></KeySet>
      </RuleParam>
      <RuleParam name="IncomingAsymmetricAlgorithm">
         <!-- <KeySet value="RSA/ECB/PKCS5Padding"> -->
         <!-- <KeySet value="RSA/ECB/PKCS#1"> (cryptix)-->
         <!-- <KeySet value="RSA/ECB/PKCS1Padding"> -->
         <!-- <KeySet value="ElGamal/ECB/PKCS#1"> -->
         <KeySet value="RSA/ECB/PKCS#1"/>
      </RuleParam>
      <!-- used to encrypt the session key -->
      <RuleParam name="OutgoingAsymmetricAlgorithm">
         <!-- PKCS#1 is not supported by the Cryptix library -->
         <KeySet value="RSA/ECB/PKCS#1"/>
      </RuleParam>
      <RuleParam name="IncomingSigningAlgorithm">
         <!-- Example of possible values:          MD2withRSA, MD5withRSA, or SHA1withRSA -->
         <KeySet value="MD5withRSA"/>
      </RuleParam>
      <RuleParam name="OutgoingSigningAlgorithm">
         <KeySet value="MD5withRSA"/>
      </RuleParam>
   </Policy>

 <Policy name="BOOTPOLICY" type="org.cougaar.core.security.policy.AccessControlPolicy">
  <RuleParam name="IncomingMessageAction">
    <KeySet value="">
      <KeyValue key="Criticality0" value="SetAside" />
      <KeyValue key="Criticality1" value="SetAside" />
      <KeyValue key="Criticality2" value="AcceptMessage" />
      <KeyValue key="Criticality3" value="AcceptMessage" />
      <KeyValue key="Criticality4" value="AcceptMessage" />
      <KeyValue key="Criticality5" value="AcceptMessage" />
    </KeySet>
  </RuleParam>

  <RuleParam name="IncomingVerb">
    <KeySet value="Transport">
	<!-- <KeyValue key="3-69-ARBN" value="Transport:AssetTransfer"/> -->
    </KeySet>
  </RuleParam>

  <RuleParam name="OutgoingVerb">
    <KeySet value="Transport">
	<!-- <KeyValue key="3-69-ARBN" value="Transport:AssetTransfer"/> -->
    </KeySet>
  </RuleParam>

  <RuleParam name="OutgoingAgentAction">
    <KeySet value="AcceptMessage">
      <!-- <KeyValue key="3-69-ARBN" value="SetAside" /> -->
      <!-- <KeyValue key="2-7-INFBN" value="SetAside" /> -->
    </KeySet>
  </RuleParam>

  <RuleParam name="IncomingAgentAction">
    <KeySet value="AcceptMessage">
      <!-- <KeyValue key="3-69-ARBN" value="SetAside" /> -->
      <!-- <KeyValue key="2-7-INFBN" value="SetAside" /> -->
    </KeySet>
  </RuleParam>

    <RuleParam name="IncomingMessageCriticality">
      <KeySet value="3">
      </KeySet>
    </RuleParam>

    <RuleParam name="OutgoingMessageCriticality">
      <KeySet value="3">
      </KeySet>
    </RuleParam>

    <RuleParam name="IncomingMessageIntegrity">
      <KeySet value="3">
      </KeySet>
    </RuleParam>

    <RuleParam name="OutgoingMessageIntegrity">
      <KeySet value="3">
      </KeySet>
    </RuleParam>

</Policy>

</Policies>

=== codeaudit/cougaar-securitycore/securityservices/test/configs/ul-mini-config-ldap/TRANSCOMCryptoPolicy.ldm.xml
<?xml version="1.0"  encoding="US-ASCII"?>

<!DOCTYPE Policy SYSTEM "Policy.ldm.dtd" []>

<Policies>

 <Policy name="TRANSCOMCryptoPolicy" type="org.cougaar.core.security.policy.CryptoPolicy">

   <!-- the following rule parameters will be used for the July demo -->

   <RuleParam name="secureMethod">
     <KeySet value="sign">
       <KeyValue key="NCA" value="signAndEncrypt" />
       <KeyValue key="3ID-HHC" value="Encrypt" />
       <KeyValue key="ALPHA-AIRLINES" value="Encrypt" />
     </KeySet>
   </RuleParam>

   <RuleParam name="symmetricAlgorithm">
     <KeySet value="">
       <KeyValue key="NCA" value="DESede" />
       <KeyValue key="3ID-HHC" value="DESede" />
       <KeyValue key="ALPHA-AIRLINES" value="DES" />
     </KeySet>
   </RuleParam>

   <RuleParam name="asymmetricAlgorithm">
     <KeySet value="">
       <KeyValue key="NCA" value="RSA/ECB/PKCS#1" />
       <KeyValue key="3ID-HHC" value="RSA/ECB/PKCS#1" />
       <KeyValue key="ALPHA-AIRLINES" value="RSA/ECB/PKCS#1" />
     </KeySet>
   </RuleParam>

   <RuleParam name="signingAlgorithm">
     <KeySet value="MD5withRSA">
       <KeyValue key="NCA" value="MD5withRSA" />
       <KeyValue key="3ID-HHC" value="MD5withRSA" />
       <KeyValue key="ALPHA-AIRLINES" value="MD2withRSA" />
     </KeySet>
   </RuleParam>

   <RuleParam name="messageSecurityManager">
     <KeySet value="org.cougaar.core.society.PublicKeyMessageSecurityManager">
       <KeyValue key="NCA" value="org.cougaar.core.society.PublicKeyMessageSecurityManager" />
       <KeyValue key="3ID-HHC" value="org.cougaar.core.society.PublicKeyMessageSecurityManager" />
       <KeyValue key="ALPHA-AIRLINES" value="org.cougaar.core.society.PublicKeyMessageSecurityManager" />
     </KeySet>
   </RuleParam>

   <RuleParam name="providerName">
     <KeySet value="">
       <KeyValue key="NCA" value="" />
       <KeyValue key="3ID-HHC" value="" />
       <KeyValue key="ALPHA-AIRLINES" value="" />
     </KeySet>
   </RuleParam>

 </Policy>

</Policies>

=== codeaudit/cougaar-securitycore/securityservices/test/configs/ul-mini-config/3-69-ARBNPolicy.ldm.xml
<?xml version="1.0"  encoding="US-ASCII"?>

<!DOCTYPE Policy SYSTEM "Policy.ldm.dtd" []>

<!-- Policies for 3-69-ARBN -->

<Policies>
 <Policy name="THREE-69-ARBNAccessControlPolicy" type="org.cougaar.core.security.AccessControlPolicy">

   <RuleParam name="agentName">
     <String value="3-69-ARBN"> </String>
   </RuleParam>

    <RuleParam name="OutgoingMessageCriticality">
      <Integer min="0" max="5" value="4" />
    </RuleParam>
    <RuleParam name="OutgoingMessageIntegrity">
      <Integer min="0" max="5" value="4" />
    </RuleParam>
 </Policy>


 <Policy name="THREE-69-ARBNCryptoPolicy" type="org.cougaar.core.security.CryptoPolicy">

   <!-- the following rule parameters will be used for the July demo -->

   <RuleParam name="secureMethod">
     <String value="signAndEncrypt"> </String>
   </RuleParam>

   <RuleParam name="symmetricAlgorithm">
     <String value="DESede"> </String>
   </RuleParam>

   <RuleParam name="asymmetricAlgorithm">
     <String value="RSA/ECB/PKCS#1"> </String>
   </RuleParam>

   <RuleParam name="signingAlgorithm">
     <String value="MD5withRSA"> </String>
   </RuleParam>

   <RuleParam name="messageSecurityManager">
     <String value="org.cougaar.core.society.PublicKeyMessageSecurityManager"> </String>
   </RuleParam>

   <RuleParam name="providerName">
     <String value=""> </String>
   </RuleParam>

 </Policy>

</Policies>

=== codeaudit/cougaar-securitycore/securityservices/test/configs/common/BootPolicy.ldm.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Policies SYSTEM "Policy.ldm.dtd" []>

<!-- Policies for BOOTPOLICY -->

<Policies>
   <Policy name="BOOTPOLICY" type="org.cougaar.core.security.policy.CryptoPolicy">
      <RuleParam name="IncomingSecureMethod">
         <KeySet value="signAndEncrypt"/>
      </RuleParam>
      <RuleParam name="OutgoingSecureMethod">
         <KeySet value="signAndEncrypt"/>
      </RuleParam>
      <RuleParam name="IncomingSymmetricAlgorithm">
         <KeySet value="DES"/>
      </RuleParam>
      <RuleParam name="OutgoingSymmetricAlgorithm">
         <KeySet value="DES"><!-- PKCS#1 is not supported by the Cryptix library --></KeySet>
      </RuleParam>
      <RuleParam name="IncomingAsymmetricAlgorithm">
         <!-- <KeySet value="RSA/ECB/PKCS5Padding"> -->
         <!-- <KeySet value="RSA/ECB/PKCS#1"> (cryptix)-->
         <!-- <KeySet value="RSA/ECB/PKCS1Padding"> -->
         <!-- <KeySet value="ElGamal/ECB/PKCS#1"> -->
         <KeySet value="RSA"/>
      </RuleParam>
      <!-- used to encrypt the session key -->
      <RuleParam name="OutgoingAsymmetricAlgorithm">
         <!-- PKCS#1 is not supported by the Cryptix library -->
         <KeySet value="RSA"/>
      </RuleParam>
      <RuleParam name="IncomingSigningAlgorithm">
         <!-- Example of possible values:          MD2withRSA, MD5withRSA, or SHA1withRSA -->
         <KeySet value="MD5withRSA"/>
      </RuleParam>
      <RuleParam name="OutgoingSigningAlgorithm">
         <KeySet value="MD5withRSA"/>
      </RuleParam>
   </Policy>

 <Policy name="BOOTPOLICY" type="org.cougaar.core.security.policy.AccessControlPolicy">
  <RuleParam name="IncomingMessageAction">
    <KeySet value="">
      <KeyValue key="Criticality0" value="SetAside" />
      <KeyValue key="Criticality1" value="SetAside" />
      <KeyValue key="Criticality2" value="AcceptMessage" />
      <KeyValue key="Criticality3" value="AcceptMessage" />
      <KeyValue key="Criticality4" value="AcceptMessage" />
      <KeyValue key="Criticality5" value="AcceptMessage" />
    </KeySet>
  </RuleParam>

  <RuleParam name="IncomingVerb">
    <KeySet value="*">
	<!--<KeyValue key="TRANSCOM" value="GetLogSupport"/>-->
	<!--<KeyValue key="3-69-ARBN" value="Transport:ProjectSupply"/>-->
	<!--<KeyValue key="703-MSB" value="none"/>-->
    </KeySet>
  </RuleParam>

  <RuleParam name="OutgoingVerb">
    <KeySet value="*">
	<!--<KeyValue key="TRANSCOM" value="GetLogSupport"/>-->
	<!--<KeyValue key="3-69-ARBN" value="Transport:ProjectSupply"/>-->
	<!--<KeyValue key="703-MSB" value="none"/>-->
    </KeySet>
  </RuleParam>

  <RuleParam name="OutgoingAgentAction">
    <KeySet value="AcceptMessage">
      <!-- <KeyValue key="3-69-ARBN" value="SetAside" /> -->
      <!-- <KeyValue key="2-7-INFBN" value="SetAside" /> -->
    </KeySet>
  </RuleParam>

  <RuleParam name="IncomingAgentAction">
    <KeySet value="AcceptMessage">
      <!-- <KeyValue key="3-69-ARBN" value="SetAside" /> -->
      <!-- <KeyValue key="2-7-INFBN" value="SetAside" /> -->
    </KeySet>
  </RuleParam>

    <RuleParam name="IncomingMessageCriticality">
      <KeySet value="3">
      </KeySet>
    </RuleParam>

    <RuleParam name="OutgoingMessageCriticality">
      <KeySet value="3">
      </KeySet>
    </RuleParam>

    <RuleParam name="IncomingMessageIntegrity">
      <KeySet value="3">
      </KeySet>
    </RuleParam>

    <RuleParam name="OutgoingMessageIntegrity">
      <KeySet value="3">
      </KeySet>
    </RuleParam>

   </Policy>

<!-- Requires User database
 -->
  <Policy name="BOOTPOLICY" type="org.cougaar.core.security.policy.LdapUserServicePolicy">
    <RuleParam name="ldapurl">
      <String value="ldap://tea:3890/"/>
    </RuleParam>
    <RuleParam name="user">
      <String value="cn=Manager,dc=couagaar,dc=org"/>
    </RuleParam>
    <RuleParam name="password">
      <String value="secret"/>
    </RuleParam>
    <RuleParam name="user_dn">
      <String value="dc=cougaar,dc=org"/>
    </RuleParam>
    <RuleParam name="role_dn">
      <String value="dc=roles,dc=cougaar,dc=org"/>
    </RuleParam>
    <RuleParam name="user_rdn">
      <String value="uid"/>
    </RuleParam>
    <RuleParam name="role_rdn">
      <String value="cn"/>
    </RuleParam>
    <RuleParam name="userClass">
      <KeySet value="1">
        <Key key="1" value="inetOrgPerson"/>
        <Key key="2" value="cougaarAcct"/>
      </KeySet>
    </RuleParam>
    <RuleParam name="roleClass">
      <KeySet value="1">
        <Key key="1" value="organizationalRole"/>
      </KeySet>
    </RuleParam>
    <RuleParam name="roleAttr">
      <String value="roleOccupant"/>
    </RuleParam>
  </Policy>

<!--
  <Policy name="BOOTPOLICY" type="org.cougaar.core.security.policy.ServletPolicy">
    <RuleParam name="allow-role">
      <KeySet value="ExerciseOne">
        <Key key="/user_admin" value="secure" />
      </KeySet>
    </RuleParam>
    <RuleParam name="auth-constraint">
      <KeySet value="ExerciseOne">
        <Key key="/user_admin*" value="EITHER" />
      </KeySet>
    </RuleParam>
  </Policy>
-->

<!-- BlackboardService read-only filter
-->
  <Policy name="BOOTPOLICY" type="org.cougaar.core.security.policy.BlackboardFiltePolicy">
    <RuleParam name="read-only-rule">
      <KeySet value="org.cougaar.core.security.crypto.ldap.admin.UserAdminServlet">
        <Key key="secure" value="write"/>
        <Key key="tomcat" value="read"/>
        <Key key="disabled" value="none"/>
      </KeySet>
    </RuleParam>
  </Policy>

</Policies>

=== codeaudit/cougaar-securitycore/securityservices/test/configs/ul-mini-config/DefaultCryptoPolicy.ldm.xml
<?xml version="1.0"  encoding="US-ASCII"?>

<!DOCTYPE Policy SYSTEM "Policy.ldm.dtd" []>

<Policies>

 <Policy name="DefaultCryptoPolicy" type="org.cougaar.core.security.policy.CryptoPolicy">

   <!-- the following rule parameters will be used for the July demo -->

   <RuleParam name="secureMethod">
     <String value="sign"> </String>
   </RuleParam>

   <RuleParam name="symmetricAlgorithm">
     <String value=""> </String>
   </RuleParam>

   <RuleParam name="asymmetricAlgorithm">
     <String value=""> </String>
   </RuleParam>

   <RuleParam name="signingAlgorithm">
     <String value="MD5withRSA"> </String>
   </RuleParam>

   <RuleParam name="messageSecurityManager">
     <String value="org.cougaar.core.society.PublicKeyMessageSecurityManager"> </String>
   </RuleParam>

   <RuleParam name="providerName">
     <String value=""> </String>
   </RuleParam>

 </Policy>

</Policies>
