<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Communities [
<!ELEMENT Communities (Community+)>
<!ELEMENT Community (Attribute+, Entity*)>
<!ATTLIST Community Name CDATA #REQUIRED>

<!ELEMENT AttributeID EMPTY>
<!ATTLIST AttributeID ID CDATA #REQUIRED>
<!ATTLIST AttributeID Access (manager|member|associate|world) #IMPLIED>

<!ELEMENT Entity (Attribute*)>
<!ATTLIST Entity Name CDATA #REQUIRED>

<!ELEMENT Attribute EMPTY>
<!ATTLIST Attribute ID CDATA #REQUIRED>
<!ATTLIST Attribute Value CDATA #REQUIRED>
]>
<Communities>

  <!--
    Example of a logistics (domain) community that has 5 members and provides 2
    externally visible roles.  Both external roles are provided by the agent
    "21-TSC-HQ".
  -->
  <Community Name="testComm">
    <Attribute ID="CommunityType"     Value="Security" />
    <!-- If CommunityManager attribute is not empty only the agents listed
         are permitted to write to this community context. -->
    <Attribute ID="CommunityManager"  Value="" />
    <Entity Name="miniNode" >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="3ID" >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
      <Attribute ID="ExternalRole" Value="TransportProvider" />
    </Entity>
    <Entity Name="1BDE" >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
      <Attribute ID="Role"         Value="AmmoSupplyProvider" />
    </Entity>
    <!--Entity Name="3-69-ARBN" >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
      <Attribute ID="Role"         Value="AmmoSupplyProvider" />
    </Entity-->
  </Community>

</Communities>
